"""Temporarily allow nullable email/contact_number

Revision ID: f9aafeb0d673
Revises: 0a244d4d7502
Create Date: 2025-10-31 12:24:29.293761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9aafeb0d673'
down_revision: Union[str, Sequence[str], None] = '0a244d4d7502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authentication', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.add_column('sections', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('templates', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_contact_number'), 'users', ['contact_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_contact_number'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=True)
    op.drop_column('templates', 'is_active')
    op.drop_column('sections', 'is_active')
    op.alter_column('authentication', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
